// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxQqu0Xk36-rVbTorGytb03r0TSS613qk',
    appId: '1:744778068663:web:d47eb2ffa425708781d332',
    messagingSenderId: '744778068663',
    projectId: 'alzheimer-app-6fada',
    authDomain: 'alzheimer-app-6fada.firebaseapp.com',
    storageBucket: 'alzheimer-app-6fada.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuIh66HfZ599NvLQSewJmaxXYN9fGkT6c',
    appId: '1:744778068663:android:8d595fa201b72fe081d332',
    messagingSenderId: '744778068663',
    projectId: 'alzheimer-app-6fada',
    storageBucket: 'alzheimer-app-6fada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQpuTmFJVDH0PNAcqT1pqWJEr-_NSDBHE',
    appId: '1:744778068663:ios:11a25526cd778ce681d332',
    messagingSenderId: '744778068663',
    projectId: 'alzheimer-app-6fada',
    storageBucket: 'alzheimer-app-6fada.appspot.com',
    iosBundleId: 'com.example.graduationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQpuTmFJVDH0PNAcqT1pqWJEr-_NSDBHE',
    appId: '1:744778068663:ios:11a25526cd778ce681d332',
    messagingSenderId: '744778068663',
    projectId: 'alzheimer-app-6fada',
    storageBucket: 'alzheimer-app-6fada.appspot.com',
    iosBundleId: 'com.example.graduationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxQqu0Xk36-rVbTorGytb03r0TSS613qk',
    appId: '1:744778068663:web:a27010b1ad9ed18b81d332',
    messagingSenderId: '744778068663',
    projectId: 'alzheimer-app-6fada',
    authDomain: 'alzheimer-app-6fada.firebaseapp.com',
    storageBucket: 'alzheimer-app-6fada.appspot.com',
  );
}
